/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.book.shop;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author mustafa khan
 */
public class modfiy_books extends javax.swing.JFrame {

    /**
     * Creates new form modfiy_books
     */
    public modfiy_books() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_lb_name = new javax.swing.JLabel();
        jLabel_new_id = new javax.swing.JLabel();
        jLabel_ds = new javax.swing.JLabel();
        j_t_id = new javax.swing.JTextField();
        j_t_description = new javax.swing.JTextField();
        j_t_name = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        j_t_old_id = new javax.swing.JTextField();
        j_lb_old_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MODIFYCATION");

        j_lb_name.setText("NEW NAME");

        jLabel_new_id.setText("NEW ID");

        jLabel_ds.setText("NEW Description");

        j_t_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_t_idActionPerformed(evt);
            }
        });

        update.setText("UPADATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        j_t_old_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_t_old_idActionPerformed(evt);
            }
        });

        j_lb_old_id.setText("OLD id ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j_lb_old_id, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_new_id, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ds, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j_lb_name, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(j_t_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(j_t_description, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(j_t_id, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(j_t_old_id)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(j_lb_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j_t_name, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_new_id, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ds, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_t_description, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_t_old_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_lb_old_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j_t_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_t_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_t_idActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String n_n=j_t_name.getText();
        String n_id=j_t_id.getText();
        String n_ds=j_t_description.getText();
      //  int id=Integer.parseInt(n_id);
        String ol_id=j_t_old_id.getText();
      //  int o_id=Integer.parseInt(ol_id);
        String url="jdbc:oracle:thin:@localhost:1521:XE ";
        try {
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    System.out.println("Driver Loaded");
                    Connection con=DriverManager.getConnection(url,"system","123");
	            System.out.println("Connection establised");       
                    String sql="UPDATE   books  SET b_id ='" + n_id + "', b_name ='" + n_n +"',b_description ='"+n_ds+"'WHERE b_id='"+ol_id+"'";
                    PreparedStatement pst=con.prepareStatement(sql);
                    JOptionPane.showMessageDialog(null, "data update");	
                    pst.executeUpdate();
                     // pst.setString(1,n_n );
       	            //  pst.setString(2, id);
                   //   pst.setInt(2, id);
                  //    pst.setString(2, n_ds);
                 //     pst.executeUpdate();
	            con.close();			         
			      
            }catch (ClassNotFoundException ex)
            {
                System.out.print("Driver not loaded");
            } 	        
            catch (SQLException ex) 
            {
                System.out.println("Connection not established");
            } 
    }//GEN-LAST:event_updateActionPerformed

    private void j_t_old_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_t_old_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_t_old_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modfiy_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modfiy_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modfiy_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modfiy_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modfiy_books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_ds;
    private javax.swing.JLabel jLabel_new_id;
    private javax.swing.JLabel j_lb_name;
    private javax.swing.JLabel j_lb_old_id;
    private javax.swing.JTextField j_t_description;
    private javax.swing.JTextField j_t_id;
    private javax.swing.JTextField j_t_name;
    private javax.swing.JTextField j_t_old_id;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
